from __future__ import annotations

# NFR 横切
NFR_PLUGIN_EXTENSION_UNAVAILABLE = "NFR_PLUGIN_EXTENSION_UNAVAILABLE"

# NFR-006 推送
PUSH_CONFIG_INVALID = "PUSH_CONFIG_INVALID"

# NFR-006 推送通道 companion
PUSH_CHANNEL_DEGRADED = "PUSH_CHANNEL_DEGRADED"
PUSH_CHANNEL_ALL_FAILED = "PUSH_CHANNEL_ALL_FAILED"

# NFR 横切 probe 超时（非阻塞）
NFR_PROBE_TIMEOUT = "NFR_PROBE_TIMEOUT"

# NFR-007 信创
XINCHUANG_NON_COMPLIANT = "XINCHUANG_NON_COMPLIANT"

# GOV-005 发布（errors 常量集中出口，publish/errors.py re-export）
GOV_PUBLISH_ENTRY_NOT_FOUND = "GOV_PUBLISH_ENTRY_NOT_FOUND"
GOV_PUBLISH_INVALID_TRANSITION = "GOV_PUBLISH_INVALID_TRANSITION"
GOV_PUBLISH_ALREADY_PENDING = "GOV_PUBLISH_ALREADY_PENDING"
GOV_PUBLISH_FORBIDDEN = "GOV_PUBLISH_FORBIDDEN"
